.TH CHAOSGAME 6 "Okt 19, 2018" "version 1.0" "Chaos Game manual"
.SH NAME
Chaos Game
.SH SYNOPSIS
.B chaos [#vertices] [#frames]
.SH DESCRIPTION
In short,
.B Chaos Game
creates fractals using the chaos game method. For more info, see the github page
.IR https://github.com/jeroenwzelf/chaos-game .
.SH OPTIONS
.TP
.B #vertices
The amount of initial vertices the program starts with.
.TP
.B #frames
The amount of frames/iterations that the program runs the algorithm for. When #frames is 0, it will run indefinitely.
.SH AUTHOR
Jeroen Donkers
.RI < jeroen.donkers@live.nl >
started writing the
.B Chaos Game
on July 10, 2015. The most recent version is available on 
.IR https://github.com/jeroenwzelf/chaos-game .
